# Generated by Django 3.2.20 on 2023-11-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('nohours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='resort_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resortname', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('image', models.FileField(upload_to='')),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('email', models.CharField(max_length=90)),
                ('phone', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=90)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('email', models.CharField(max_length=90)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='room_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=90)),
                ('image', models.FileField(upload_to='')),
                ('roomno', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
                ('rate', models.FloatField()),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.resort_table')),
            ],
        ),
        migrations.CreateModel(
            name='rating_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('date', models.DateField()),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.resort_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('payment', models.FloatField()),
                ('date', models.DateField()),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.booking_table')),
            ],
        ),
        migrations.CreateModel(
            name='facilities_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('facilities', models.TextField()),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.resort_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compaint', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=500)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='RESORT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.resort_table'),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.user_table'),
        ),
    ]
