# Generated by Django 3.2.20 on 2023-11-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0003_chat_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='image',
            field=models.FileField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
