# Generated by Django 3.2.20 on 2023-11-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0006_alter_location_latitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
