# Generated by Django 3.2.20 on 2023-11-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0007_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort_table',
            name='lattitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resort_table',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
