# Generated by Django 3.2.20 on 2023-11-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0008_auto_20231109_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort_table',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resort_table',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
