# Generated by Django 3.2.21 on 2023-11-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0009_auto_20231109_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_table',
            name='nohours',
        ),
    ]
